### ISSUE TITLE
Feature request: solr-exporter

### ISSUE THREAD

**Issue by alexangas** [freedev/solrcloud-zookeeper-kubernetes#10]
Firstly, thank you for this awesome resource. It has been really helpful for my understanding.

I was just wondering what your thoughts might be for adding solr-exporter to this, or if it would be out of scope?

**Comment by freedev** [comment]
Hi @alexangas, 
I wrote another project to export/import backup/restore solr indexes. 
https://github.com/freedev/solr-import-export-json

The purpose of this project is only to help people to deploy SolrCloud in a kube env

**Comment by freedev** [comment]
I forgot to mention that Solr (so even SolrCloud) has already his own export features, just have a look at Solr Documentation
https://lucene.apache.org/solr/guide/8_7/exporting-result-sets.html

**Comment by alexangas** [comment]
Thanks for that information, I wasn't aware of those options and they will be useful for the future!

I apologise as I wasn't very specific, but what I was actually referring to was this solr-exporter:  https://lucene.apache.org/solr/guide/7_3/monitoring-solr-with-prometheus-and-grafana.html#starting-the-exporter. That is, something that exports metrics to Prometheus. I just wasn't sure if that was going outside the goals of this project.
