### ISSUE TITLE
Multiple solr nodes

### ISSUE THREAD

**Issue by jefferyyuan** [freedev/solrcloud-zookeeper-kubernetes#2]
We can only run one solr node using provided kubernetes files, could you please update it so we can run multiple solr nodes?
Thanks.

**Comment by piratebriggs** [comment]
You could have a look at #5 - You'll need a ScaledSet, switch to using a volumeClaimTemplates and some way for the solr nodes to discover each other - I use a headless service in the PR which follows the ZooKeeper example published on [kubernetes.io](https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/)

**Comment by freedev** [comment]
Hi, I've just added a new AKS configuration for multiple Solr and Zookeeper nodes. If someone has time and desire to test it any contribution is really appreciated. Have a look at `start-aks-solr-cluster.sh` and `start-aks-zookeeper-ensemble.sh` scripts.

**Comment by freedev** [comment]
Hi, I've redesigned the solution. Now there is full support for multiple node configuration.
