### ISSUE TITLE
unable to downgrade solr version

### ISSUE THREAD

**Issue by liaogz82** [freedev/solrcloud-zookeeper-kubernetes#3]
Hi, it seems that I cannot downgrade solr to version 5.5.5. Are you able to look into it?

**Comment by freedev** [comment]
Hi Liao, I'm sorry, just returned to work and I'm facing a really busy period. Have you found any error in the logs?

**Comment by liaogz82** [comment]
I am on leave at the moment and have no access to the laptop. I will get back to you tomorrow once I get my hands on it

**Comment by freedev** [comment]
I've closed the issue because no error was provided.
