### ISSUE TITLE
Solr won't start

### ISSUE THREAD

**Issue by pascal-cbs** [freedev/solrcloud-zookeeper-kubernetes#6]
After deploying to AKS Kubernetes cluster, we experience the following error. Do you have a solution for this kind of error ? Tried both cluster as the zookeeper version.

```
javax.servlet.ServletException: javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.
```

**Comment by sourabh10995** [comment]
I figured out the issue.
In this file /services/service-zookeeper.yml change the targetPort to 2181 since Zookeeper is locally running in 2181.

**Comment by pascal-cbs** [comment]
> I figured out the issue.
> In this file /services/service-zookeeper.yml change the targetPort to 2181 since Zookeeper is locally running in 2181.

Seems to work. Thanks a lot! 
@freedev : should I create a PR ?

**Comment by freedev** [comment]
could you please submit pull request with the fix?

**Comment by pascal-cbs** [comment]
> could you please submit pull request with the fix?

I do not have access to your repo. Can you just change targetPort: 2181 in the file service-zookeeper.yml ?

Another question. Is there a possibility to copy index files to the /store/data directory ?

**Comment by freedev** [comment]
git in general, and github in particular, gives the opportunity to [create a pull request](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) with the change you think should be useful. This is let anyone to contribute to any project.

**Comment by freedev** [comment]
If we need to change only the targetPort to 2181, very likely I can do it myself.

**Comment by freedev** [comment]
Done
