### ISSUE TITLE
use solr out of k8s cluster

### ISSUE THREAD

**Issue by necipakca** [freedev/solrcloud-zookeeper-kubernetes#9]
This is amazing resource thanks for share it. It saves me lots of time. 👍

I'm trying to use solr from out of cluster. Even I use "HttpSolrClient" java client it tries to connect internal k8s solr address.

java.net.UnknownHostException: solr-0.solrcluster: nodename nor servname provided, or not known

What is the proper way  to use solr from out of cluster ?
Because developers are have to connect this solr cluster from their own IDE.

**Comment by freedev** [comment]
Hi, thanks. Can you share the code you're using with HttpSolrClient?

**Comment by necipakca** [comment]
Hi,

solr.10.100.100.100.nip.io is ingress controller.

HttpSolrClient  cloudSolrClient =new HttpSolrClient.Builder()
                    .withHttpClient(client)
                    .withConnectionTimeout(10000)
                    .withSocketTimeout(60000)
                    .withBaseSolrUrl("http://solr.10.100.100.100.nip.io/solr")
                    .build();

cloudSolrClient.query("TEST_C",solrQuery, SolrRequest.METHOD.POST);

this throw error : 

java.lang.RuntimeException: Tried fetching cluster state using the node names we knew of, i.e. [solr-1.solrcluster:8983_solr, solr-2.solrcluster:8983_solr, solr-0.solrcluster:8983_solr]. However, succeeded in obtaining the cluster state from none of them.If you think your Solr cluster is up and is accessible, you could try re-creating a new CloudSolrClient using working solrUrl(s) or zkHost(s)

**Comment by freedev** [comment]
Why not just 

String solrUrl = "http://solr.10.100.100.100.nip.io/solr";
SolrClient solrClient = new HttpSolrClient.Builder(solrUrl)
    .withConnectionTimeout(10000)
    .withSocketTimeout(60000)
    .build();

**Comment by necipakca** [comment]
Thanks ,
The problem was cache :( 
HttpSolrClient works fine like  u said.
